### ISSUE TITLE
Debug CORS 

### ISSUE THREAD

**Issue by AXinx** [AXinx/Log2Pro#3]
When Prise(port, 9081) tries to request data from Prometheus(port, 9090), will cause a CORS error.

**Comment by skoulouzis** [comment]
Which workflow should we run to reproduce the error?

**Comment by AXinx** [comment]
> Which workflow should we run to reproduce the error?
The demo_workflow.t2flow in docker_workflow file

**Comment by AXinx** [comment]
The problem happens in getData.js.
It's the axios.get has some error. https://github.com/AXinx/Log2Pro/blob/6fd334580088e3ef7a4edfb9ebc7809e562f20e1/PRovenanceIntegratorSErvice/src/main/resources/public/getData.js#L143

I think the url here is a little stranger, it's not Prometheus retrive api. I don't know what it is. 

Also, I am not sure is the dbConnector here right.  https://github.com/AXinx/Log2Pro/blob/6fd334580088e3ef7a4edfb9ebc7809e562f20e1/PRovenanceIntegratorSErvice/src/main/resources/public/getData.js#L3 
Because the port 8080 is not defined. Port of cAdvisor is 8082. Port of Prometheus is 9090. 

You can ignore line 9-21, which is only for.

**Comment by AXinx** [comment]
Thank you very much. 
I have tested and the "CORS" error disappeared. 
But, after request, no data return. 
<img width="1427" alt="Screenshot 2020-04-02 at 15 52 35" src="https://user-images.githubusercontent.com/10726118/78257984-df95bd80-74fa-11ea-8c36-a44a536d2292.png">

So I still want to ask how to solve this problem.  
Is this the dbConnector port wrong? 
Or the query url to Prometheus is not correct?
